name: flannel-images

on:
  push:
    tags:
      - v*
  pull_request:
    paths:
      - "kubeadm/flannel/**"
      - "kubeadm/buildx.psm1"
      - ".github/workflows/flannel.yml"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: pwsh
        working-directory: ./kubeadm/flannel
    steps:
    - uses: actions/checkout@v2
    - name: Build and push images
      if: ${{ github.event_name == 'push' }}
      run: |
        echo ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        $gittag = ($env:GITHUB_REF -split '/' | select-object -skip 2) -join '/'
        ./build.ps1 -push -tagSuffix $gittag
    - name: Build images (without push)
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        ./build.ps1
